; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "FC Technologies"
#define MyAppVersion "1.7"
#define MyAppPublisher "FC Technologies"
#define MyAppURL "www.flicontech.com"
#define MyAppExeName "FCTechnologies.exe"
#define MyAppAssocName MyAppName + " Setup"
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2D2E5601-A100-4D08-964C-1044D120186D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\FCTechnologies
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=FCTechnologiesInstaller
SetupIconFile=C:\Users\Viktor\Desktop\FCTech\Icon_Installer_04.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\CubeProgrammer_API.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\DebugAuthPermissions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\FileManager.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\HSM_P11_Lib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\hub.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\libeay32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\mfc120.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\msvcp120.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\msvcp140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\msvcp140d.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\msvcr100.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\msvcr120.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\Preparation.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\psa_sdm.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\Qt5Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\Qt5DBus.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\Qt5Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\Qt5Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\Qt5Script.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\Qt5SerialPort.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\Qt5Xml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\Qt5XmlPatterns.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\screen_retriever_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\stlibp11_SAM.conf"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\stlibp11_SAM.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\STLinkUSBDriver.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\ucrtbased.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\vcruntime140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\vcruntime140_1d.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\vcruntime140d.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\version"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\window_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\xerces-c_3_1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Release1.6\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Viktor\Desktop\FCTech\Driver\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Viktor\Downloads\VC_redist.x64.exe"; DestDir: "{app}"; AfterInstall: RunOtherInstaller
Source: "C:\Users\Viktor\Desktop\FCTech\Driver\installer_x64.exe"; DestDir: "{app}"; AfterInstall: RunOtherInstaller2
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Code]
procedure RunOtherInstaller;
var
  ResultCode: Integer;
begin
  if not Exec(ExpandConstant('{app}\VC_redist.x64.exe'), '', '', SW_SHOWNORMAL,
    ewWaitUntilTerminated, ResultCode)
  then
    MsgBox('Other installer failed to run!' + #13#10 +
      SysErrorMessage(ResultCode), mbError, MB_OK);
end;
[Code]
procedure RunOtherInstaller2;
var
  ResultCode: Integer;
begin
  if not Exec(ExpandConstant('{app}\installer_x64.exe'), '', '', SW_SHOWNORMAL,
    ewWaitUntilTerminated, ResultCode)
  then
    MsgBox('Other installer 2 failed to run!' + #13#10 +
      SysErrorMessage(ResultCode), mbError, MB_OK);
end;

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

