syntax = "proto3";
package report_message;

message ReportMessage {
    uint32 id = 1;
    uint64 buttons = 2;
    uint32 x = 3;
    uint32 y = 4;
    uint32 z = 5;
    uint32 rx = 6;
    uint32 ry = 7;
    uint32 rz = 8;
    uint32 slider = 9;

    bool b1 = 10;
    bool b2 = 11;
    bool b3 = 12;
    bool b4 = 13;
    bool b5 = 14;
    bool b6 = 15;
    bool b7 = 16;
    bool b8 = 17;
    bool b9 = 18;
    bool b10 = 19;
    bool b11 = 20;
    bool b12 = 21;
    bool b13 = 22;
    bool b14 = 23;
    bool b15 = 24;
    bool b16 = 25;
    bool b17 = 26;
    bool b18 = 27;
    bool b19 = 28;
    bool b20 = 29;
    bool b21 = 30;
    bool b22 = 31;
    bool b23 = 32;
    bool b24 = 33;
    bool b25 = 34;
    bool b26 = 35;
    bool b27 = 36;
    bool b28 = 37;
    bool b29 = 38;
    bool b30 = 39;
    bool b31 = 40;
    bool b32 = 41;
    bool b33 = 42;
    bool b34 = 43;
    bool b35 = 44;
    bool b36 = 45;
    bool b37 = 46;
    bool b38 = 47;
    bool b39 = 48;
    bool b40 = 49;
    bool b41 = 50;
    bool b42 = 51;
    bool b43 = 52;
    bool b44 = 53;
    bool b45 = 54;
    bool b46 = 55;
    bool b47 = 56;
    bool b48 = 57;
    bool b49 = 58;

    uint32 fid = 59;
    int32 x_min = 60;
    int32 x_centr = 61;
    int32 x_max = 62;
    uint32 x_averaging = 63;
    uint32 x_dead_zone = 64;
    int32 y_min = 65;
    int32 y_centr = 66;
    int32 y_max = 67;
    uint32 y_averaging = 68;
    uint32 y_dead_zone = 69;
    int32 z_min = 70;
    int32 z_centr = 71;
    int32 z_max = 72;
    uint32 z_averaging = 73;
    uint32 z_dead_zone = 74;
    int32 rx_min = 75;
    int32 rx_centr = 76;
    int32 rx_max = 77;
    uint32 rx_averaging = 78;
    uint32 rx_dead_zone = 79;
    int32 ry_min = 80;
    int32 ry_centr = 81;
    int32 ry_max = 82;
    uint32 ry_averaging = 83;
    uint32 ry_dead_zone = 84;
    int32 rz_min = 85;
    int32 rz_max = 87;
    uint32 rz_averaging = 88;
    uint32 rz_dead_zone = 89;
    int32 slider_min = 90;
    int32 slider_max = 91;
    uint32 slider_averaging = 92;
    uint32 slider_dead_zone = 93;
    uint32 encoder_time = 94;
    uint32 led_r = 95;
    uint32 led_g = 96;
    uint32 led_b = 97;
    uint32 id_grib = 98;
    uint32 hatka1_mode = 99;
    uint32 hatka2_mode = 100;
    uint32 hatka3_mode = 101;
    uint32 hatka4_mode = 102;
    uint32 control_byte = 103;
    uint32 gash_button1_min = 104;
    uint32 gash_button1_max = 105;
    uint32 gash_button2_min = 106;
    uint32 gash_button2_max = 107;
    uint32 gash_button3_min = 108;
    uint32 gash_button3_max = 109;
    int32 spi_error_cnt = 110;
    uint64 fbuttons = 111;
    int32 x_axis = 112;
    int32 y_axis = 113;
    int32 z_axis = 114;
    int32 rx_axis = 115;
    int32 ry_axis = 116;
    int32 rz_axis = 117;
    int32 slider_axis = 118;
    uint32 fw_version = 119;

    bool connected = 120;
    string base_name = 121;
    string side = 122;
    bool more_than_two = 123;
    bool dfu_on = 124;

    bool inverted_x = 125;
    bool inverted_y = 126;
    bool inverted_z = 127;
    bool inverted_rx = 128;
    bool inverted_ry = 129;
    bool inverted_rz = 130;
}
