syntax = "proto3";
package report_in_message;

message ReportInMessage { 
    uint32 id = 1;
    uint64 buttons = 2;
    uint32 x = 3;
    uint32 y = 4;
    uint32 z = 5;
    uint32 rx = 6;
    uint32 ry = 7;
    uint32 rz = 8;
    uint32 slider = 9;
    bool b1 = 10;
    bool b2 = 11;
    bool b3 = 12;
    bool b4 = 13;
    bool b5 = 14;
    bool b6 = 15;
    bool b7 = 16;
    bool b8 = 17;
    bool b9 = 18;
    bool b10 = 19;
    bool b11 = 20;
    bool b12 = 21;
    bool b13 = 22;
    bool b14 = 23;
    bool b15 = 24;
    bool b16 = 25;
    bool b17 = 26;
    bool b18 = 27;
    bool b19 = 28;
    bool b20 = 29;
    bool b21 = 30;
    bool b22 = 31;
    bool b23 = 32;
    bool b24 = 33;
    bool b25 = 34;
    bool b26 = 35;
    bool b27 = 36;
    bool b28 = 37;
    bool b29 = 38;
    bool b30 = 39;
    bool b31 = 40;
    bool b32 = 41;
    bool b33 = 42;
    bool b34 = 43;
    bool b35 = 44;
    bool b36 = 45;
    bool b37 = 46;
    bool b38 = 47;
    bool b39 = 48;
    bool b40 = 49;
    bool b41 = 50;
    bool b42 = 51;
    bool b43 = 52;
    bool b44 = 53;
    bool b45 = 54;
    bool b46 = 55;
    bool b47 = 56;
    bool b48 = 57;
    bool b49 = 58;

}

