#[derive(Clone, Debug)]
pub struct Buttons {
    pub b1: bool,
    pub b2: bool,
    pub b3: bool,
    pub b4: bool,
    pub b5: bool,
    pub b6: bool,
    pub b7: bool,
    pub b8: bool,
    pub b9: bool,
    pub b10: bool,
    pub b11: bool,
    pub b12: bool,
    pub b13: bool,
    pub b14: bool,
    pub b15: bool,
    pub b16: bool,
    pub b17: bool,
    pub b18: bool,
    pub b19: bool,
    pub b20: bool,
    pub b21: bool,
    pub b22: bool,
    pub b23: bool,
    pub b24: bool,
    pub b25: bool,
    pub b26: bool,
    pub b27: bool,
    pub b28: bool,
    pub b29: bool,
    pub b30: bool,
    pub b31: bool,
    pub b32: bool,
    pub b33: bool,
    pub b34: bool,
    pub b35: bool,
    pub b36: bool,
    pub b37: bool,
    pub b38: bool,
    pub b39: bool,
    pub b40: bool,
    pub b41: bool,
    pub b42: bool,
    pub b43: bool,
    pub b44: bool,
    pub b45: bool,
    pub b46: bool,
    pub b47: bool,
    pub b48: bool,
    pub b49: bool,
}

impl Buttons {
    pub fn new(bits: u64) -> Self {
        const SHIFT_CONST: u64 = 15;
        Self {
             b1: (bits & (1 << (0 + SHIFT_CONST))) != 0,
             b2: (bits & (1 << (1 + SHIFT_CONST))) != 0,
             b3: (bits & (1 << (2 + SHIFT_CONST))) != 0,
             b4: (bits & (1 << (3 + SHIFT_CONST))) != 0,
             b5: (bits & (1 << (4 + SHIFT_CONST))) != 0,
             b6: (bits & (1 << (5 + SHIFT_CONST))) != 0,
             b7: (bits & (1 << (6 + SHIFT_CONST))) != 0,
             b8: (bits & (1 << (7 + SHIFT_CONST))) != 0,
             b9: (bits & (1 << (8 + SHIFT_CONST))) != 0,
            b10: (bits & (1 << (9 + SHIFT_CONST))) != 0,
            b11: (bits & (1 << (10 + SHIFT_CONST))) != 0,
            b12: (bits & (1 << (11 + SHIFT_CONST))) != 0,
            b13: (bits & (1 << (12 + SHIFT_CONST))) != 0,
            b14: (bits & (1 << (13 + SHIFT_CONST))) != 0,
            b15: (bits & (1 << (14 + SHIFT_CONST))) != 0,
            b16: (bits & (1 << (15 + SHIFT_CONST))) != 0,
            b17: (bits & (1 << (16 + SHIFT_CONST))) != 0,
            b18: (bits & (1 << (17 + SHIFT_CONST))) != 0,
            b19: (bits & (1 << (18 + SHIFT_CONST))) != 0,
            b20: (bits & (1 << (19 + SHIFT_CONST))) != 0,
            b21: (bits & (1 << (20 + SHIFT_CONST))) != 0,
            b22: (bits & (1 << (21 + SHIFT_CONST))) != 0,
            b23: (bits & (1 << (22 + SHIFT_CONST))) != 0,
            b24: (bits & (1 << (23 + SHIFT_CONST))) != 0,
            b25: (bits & (1 << (24 + SHIFT_CONST))) != 0,
            b26: (bits & (1 << (25 + SHIFT_CONST))) != 0,
            b27: (bits & (1 << (26 + SHIFT_CONST))) != 0,
            b28: (bits & (1 << (27 + SHIFT_CONST))) != 0,
            b29: (bits & (1 << (28 + SHIFT_CONST))) != 0,
            b30: (bits & (1 << (29 + SHIFT_CONST))) != 0,
            b31: (bits & (1 << (30 + SHIFT_CONST))) != 0,
            b32: (bits & (1 << (31 + SHIFT_CONST))) != 0,
            b33: (bits & (1 << (32 + SHIFT_CONST))) != 0,
            b34: (bits & (1 << (33 + SHIFT_CONST))) != 0,
            b35: (bits & (1 << (34 + SHIFT_CONST))) != 0,
            b36: (bits & (1 << (35 + SHIFT_CONST))) != 0,
            b37: (bits & (1 << (36 + SHIFT_CONST))) != 0,
            b38: (bits & (1 << (37 + SHIFT_CONST))) != 0,
            b39: (bits & (1 << (38 + SHIFT_CONST))) != 0,
            b40: (bits & (1 << (39 + SHIFT_CONST))) != 0,
            b41: (bits & (1 << (40 + SHIFT_CONST))) != 0,
            b42: (bits & (1 << (41 + SHIFT_CONST))) != 0,
            b43: (bits & (1 << (42 + SHIFT_CONST))) != 0,
            b44: (bits & (1 << (43 + SHIFT_CONST))) != 0,
            b45: (bits & (1 << (44 + SHIFT_CONST))) != 0,
            b46: (bits & (1 << (45 + SHIFT_CONST))) != 0,
            b47: (bits & (1 << (46 + SHIFT_CONST))) != 0,
            b48: (bits & (1 << (47 + SHIFT_CONST))) != 0,
            b49: (bits & (1 << (48 + SHIFT_CONST))) != 0,
        }
    }
}